// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddCommentButton: typeof import('./src/components/AddCommentButton.vue')['default']
    AnimatedButton: typeof import('./src/components/AnimatedButton.vue')['default']
    Blog: typeof import('./src/components/Blog.vue')['default']
    Comment: typeof import('./src/components/Comment.vue')['default']
    copy: typeof import('./src/components/DeleteCommentButton copy.vue')['default']
    CyberButton: typeof import('./src/components/CyberButton.vue')['default']
    DeleteCommentButton: typeof import('./src/components/DeleteCommentButton.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    LoginDialog2: typeof import('./src/components/LoginDialog2.vue')['default']
    LogoRing: typeof import('./src/components/LogoRing.vue')['default']
    ReplyButton: typeof import('./src/components/ReplyButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    TagBar: typeof import('./src/components/TagBar.vue')['default']
    TagButton: typeof import('./src/components/TagButton.vue')['default']
    TrophyButton: typeof import('./src/components/TrophyButton.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
